# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZamZamTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'RxSwift'
  pod 'RxSwiftExt'
  pod 'RxCocoa'
  pod 'RxFeedback'
  pod 'SwifterSwift'
  pod 'SnapKit', '5.0.0'
  pod 'Then'
  pod 'SwifterSwift'
  use_frameworks!

  # Pods for ZamZamTest

end
